"""Unit tests for scripts/verify_action.py — Sprint 5/E2 Phase E.

Exercises the composite action's Python entry-point end-to-end against the
fixtures generated by `tests/fixtures/generate_fixtures.py`. Covers:

  - TestEndToEnd (4)         — happy + tampered-digest + expired + replay-detected
  - TestKeyFingerprint (1)   — drift → AttestationKeyFingerprintMismatch
  - TestPolicyVersion (1)    — mismatch → AttestationPolicyVersionMismatch
  - TestEnvelopeShape (2)    — malformed JSON + dataclass shape failure
  - TestEnvelopeParsing (2)  — inline JSON + @path-prefixed file
  - TestOutputEmission (1)   — KEY=VALUE format to $GITHUB_OUTPUT
  - TestWarningOnNoReplayStore (1) — warning emitted when replay-store-path unset
  - TestPhase2Regression (7) — incl. the guard that AEGIS_KEYS_DIR_OVERRIDE /
    AEGIS_POLICY_PATH_OVERRIDE are ignored without AEGIS_INTERNAL_FIXTURE_MODE

19 tests total (an earlier docstring said 13 — TestPhase2Regression postdates
it and the count was never reconciled). Run via:
    cd aegis-policy
    pip install --no-deps --require-hashes --only-binary=:all: -r requirements-verify-ci.txt
    pytest tests/test_verify_action.py -v
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest
import yaml

# Every test here shells out to scripts/verify_action.py, which imports
# aegis-governance[verify] — public PyPI, installed in CI from
# requirements-verify-ci.txt. Without it, 18 of these 19 fail. The marker lets
# tests.yml partition the suite by capability rather than hardcoded path: the
# required matrix job deselects this file (its venv deliberately excludes the
# SDK), and the advisory `verifier-kit` job selects exactly it — see
# pytest.ini for why that is more durable than `--ignore`.
#
# (The marker was `needs_secrets` until 2026-07-29 — a name asserting a
# private-SDK-behind-a-token premise that was false since the 2026-05-15 PyPI
# publish. These tests now run on every PR, advisory until promoted.)
pytestmark = pytest.mark.needs_aegis_sdk

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPT = REPO_ROOT / "scripts" / "verify_action.py"
FIXTURES = REPO_ROOT / "tests" / "fixtures"
MANIFEST = json.loads((FIXTURES / "manifest.json").read_text())


def _run_verify(
    env_overrides: dict[str, str],
    *,
    github_output_path: Path | None = None,
    cwd: Path | None = None,
) -> tuple[int, str, str, dict[str, str]]:
    """Run verify_action.py as a subprocess. Return (rc, stdout, stderr, outputs).

    `outputs` is parsed from $GITHUB_OUTPUT if provided, otherwise from the
    ::github-output:: stdout block emitted by verify_action.py in local mode.
    """
    env = os.environ.copy()
    # Isolate the subprocess from both AEGIS_* AND GITHUB_* inherited vars
    # so a developer running pytest inside a host Actions environment (or
    # with a stale GITHUB_OUTPUT from a prior interrupted run) doesn't have
    # outputs leak into the parent's $GITHUB_OUTPUT file. /quality-gate
    # Phase 2 cycle 1 remediation of Lane B Agent 1 F5.
    for key in list(env):
        if key.startswith("AEGIS_") or key.startswith("GITHUB_"):
            del env[key]
    env.update(env_overrides)
    if github_output_path is not None:
        env["GITHUB_OUTPUT"] = str(github_output_path)
    if cwd is not None:
        env["GITHUB_WORKSPACE"] = str(cwd)

    result = subprocess.run(
        [sys.executable, str(SCRIPT)],
        env=env,
        capture_output=True,
        text=True,
        cwd=cwd or REPO_ROOT,
    )

    outputs: dict[str, str] = {}
    if github_output_path is not None and github_output_path.exists():
        for line in github_output_path.read_text().splitlines():
            if "=" in line:
                key, _, value = line.partition("=")
                outputs[key] = value
    else:
        # Parse the ::github-output:: stdout block
        in_block = False
        for line in result.stdout.splitlines():
            if line.strip() == "::github-output::":
                in_block = True
                continue
            if in_block and "=" in line:
                key, _, value = line.partition("=")
                outputs[key] = value
    return result.returncode, result.stdout, result.stderr, outputs


def _common_env() -> dict[str, str]:
    """Standard env-var overrides routing verify_action.py to test fixtures.

    Sets AEGIS_INTERNAL_FIXTURE_MODE=1 as the sentinel gate that enables the
    AEGIS_KEYS_DIR_OVERRIDE + AEGIS_POLICY_PATH_OVERRIDE env vars (see
    scripts/verify_action.py::_fixture_mode_enabled — /quality-gate Phase 3
    ultrathink probe 4 remediation). Production consumers never set the
    sentinel, so override env vars are silently ignored there.
    """
    return {
        "AEGIS_INTERNAL_FIXTURE_MODE": "1",
        "AEGIS_KEYS_DIR_OVERRIDE": str(FIXTURES / "test-keys"),
        "AEGIS_POLICY_PATH_OVERRIDE": str(FIXTURES / "policy-test-v1.yaml"),
    }


# ─────────────────────────────────────────────────────────────────────────────
# TestEndToEnd — exercise the full pipeline against committed fixtures
# ─────────────────────────────────────────────────────────────────────────────

class TestEndToEnd:
    def test_valid_envelope_happy_path(self, tmp_path: Path):
        """envelope-valid-preview.json + matching digest → valid=true."""
        m = MANIFEST["envelope_valid_preview"]
        env = _common_env()
        env.update({
            "AEGIS_ENVELOPE": f"@{FIXTURES / m['path']}",
            "AEGIS_EXPECTED_DIGEST": m["artifact_digest"],
            "AEGIS_EXPECTED_ENVIRONMENT": m["environment"],
            "AEGIS_REPLAY_STORE_PATH": str(tmp_path / ".replay.log"),
        })
        rc, _, _, outputs = _run_verify(
            env, github_output_path=tmp_path / "outputs", cwd=tmp_path
        )
        assert rc == 0, f"unexpected non-zero rc: {outputs}"
        assert outputs["valid"] == "true"
        assert outputs["error-class"] == ""
        assert outputs["decision-id"] == m["decision_id"]
        assert outputs["artifact-digest"] == m["artifact_digest"]
        assert outputs["environment"] == "preview"
        assert outputs["policy-version"] == m["policy_version"]
        assert outputs["replay-checked"] == "true"

    def test_tampered_digest_fails(self, tmp_path: Path):
        """envelope-tampered-digest.json + wrong expected-digest → AttestationDigestMismatch."""
        m = MANIFEST["envelope_tampered_digest"]
        env = _common_env()
        env.update({
            "AEGIS_ENVELOPE": f"@{FIXTURES / m['path']}",
            "AEGIS_EXPECTED_DIGEST": m["tampered_expected_digest"],
            "AEGIS_EXPECTED_ENVIRONMENT": m["environment"],
        })
        rc, _, _, outputs = _run_verify(env, github_output_path=tmp_path / "outputs")
        assert rc == 1
        assert outputs["valid"] == "false"
        assert outputs["error-class"] == "AttestationDigestMismatch"

    def test_expired_envelope_fails(self, tmp_path: Path):
        """envelope-expired.json → AttestationExpired."""
        m = MANIFEST["envelope_expired"]
        env = _common_env()
        env.update({
            "AEGIS_ENVELOPE": f"@{FIXTURES / m['path']}",
            "AEGIS_EXPECTED_DIGEST": m["artifact_digest"],
            "AEGIS_EXPECTED_ENVIRONMENT": m["environment"],
        })
        rc, _, _, outputs = _run_verify(env, github_output_path=tmp_path / "outputs")
        assert rc == 1
        assert outputs["valid"] == "false"
        assert outputs["error-class"] == "AttestationExpired"

    def test_replay_detected_on_second_call(self, tmp_path: Path):
        """Same envelope + same replay-store-path twice → AttestationReplayDetected."""
        m = MANIFEST["envelope_valid_preview"]
        replay_log = tmp_path / ".replay.log"
        env = _common_env()
        env.update({
            "AEGIS_ENVELOPE": f"@{FIXTURES / m['path']}",
            "AEGIS_EXPECTED_DIGEST": m["artifact_digest"],
            "AEGIS_EXPECTED_ENVIRONMENT": m["environment"],
            "AEGIS_REPLAY_STORE_PATH": str(replay_log),
        })

        # First call: success + decision_id appended
        rc1, _, _, outputs1 = _run_verify(
            env, github_output_path=tmp_path / "outputs1", cwd=tmp_path
        )
        assert rc1 == 0
        assert outputs1["valid"] == "true"
        assert outputs1["replay-checked"] == "true"

        # Second call: replay detected
        rc2, _, _, outputs2 = _run_verify(
            env, github_output_path=tmp_path / "outputs2", cwd=tmp_path
        )
        assert rc2 == 1
        assert outputs2["valid"] == "false"
        assert outputs2["error-class"] == "AttestationReplayDetected"
        # Predicate fields ARE populated on this failure (parse happened pre-check)
        assert outputs2["decision-id"] == m["decision_id"]
        assert outputs2["replay-checked"] == "true"


# ─────────────────────────────────────────────────────────────────────────────
# TestKeyFingerprint — drift between bytes + policy
# ─────────────────────────────────────────────────────────────────────────────

class TestKeyFingerprint:
    def test_drifted_policy_fingerprint_fails(self, tmp_path: Path):
        """Policy fingerprint ≠ SHA-256 over key bytes → AttestationKeyFingerprintMismatch."""
        # Copy test policy + mutate fingerprint
        test_policy = yaml.safe_load((FIXTURES / "policy-test-v1.yaml").read_text())
        test_policy["required_keyids"]["ed25519"] = "0" * 64  # plausibly-formatted but wrong
        bad_policy_path = tmp_path / "policy-bad.yaml"
        bad_policy_path.write_text(yaml.safe_dump(test_policy, sort_keys=False))

        m = MANIFEST["envelope_valid_preview"]
        env = _common_env()
        env["AEGIS_POLICY_PATH_OVERRIDE"] = str(bad_policy_path)
        env.update({
            "AEGIS_ENVELOPE": f"@{FIXTURES / m['path']}",
            "AEGIS_EXPECTED_DIGEST": m["artifact_digest"],
            "AEGIS_EXPECTED_ENVIRONMENT": m["environment"],
        })
        rc, _, _, outputs = _run_verify(env, github_output_path=tmp_path / "outputs")
        assert rc == 1
        assert outputs["valid"] == "false"
        assert outputs["error-class"] == "AttestationKeyFingerprintMismatch"


# ─────────────────────────────────────────────────────────────────────────────
# TestPolicyVersion — strict-equal mismatch
# ─────────────────────────────────────────────────────────────────────────────

class TestPolicyVersion:
    def test_explicit_policy_version_mismatch(self, tmp_path: Path):
        """AEGIS_POLICY_VERSION_EXPECTED != envelope policy_version → mismatch."""
        m = MANIFEST["envelope_valid_preview"]
        env = _common_env()
        env.update({
            "AEGIS_ENVELOPE": f"@{FIXTURES / m['path']}",
            "AEGIS_EXPECTED_DIGEST": m["artifact_digest"],
            "AEGIS_EXPECTED_ENVIRONMENT": m["environment"],
            "AEGIS_POLICY_VERSION_EXPECTED": "9.9.9",  # arbitrary mismatch
        })
        rc, _, _, outputs = _run_verify(env, github_output_path=tmp_path / "outputs")
        assert rc == 1
        assert outputs["valid"] == "false"
        assert outputs["error-class"] == "AttestationPolicyVersionMismatch"
        # Predicate fields populated (mismatch is detected post-verify, post-parse)
        assert outputs["policy-version"] == m["policy_version"]


# ─────────────────────────────────────────────────────────────────────────────
# TestEnvelopeShape — malformed envelope inputs
# ─────────────────────────────────────────────────────────────────────────────

class TestEnvelopeShape:
    def test_malformed_json_input(self, tmp_path: Path):
        env = _common_env()
        env.update({
            "AEGIS_ENVELOPE": "{not valid json",
            "AEGIS_EXPECTED_DIGEST": "a" * 64,
            "AEGIS_EXPECTED_ENVIRONMENT": "preview",
        })
        rc, _, _, outputs = _run_verify(env, github_output_path=tmp_path / "outputs")
        assert rc == 1
        assert outputs["error-class"] == "AttestationEnvelopeShapeInvalid"

    def test_valid_json_but_wrong_shape(self, tmp_path: Path):
        env = _common_env()
        env.update({
            # Valid JSON, but not a DSSE envelope
            "AEGIS_ENVELOPE": '{"not": "an envelope"}',
            "AEGIS_EXPECTED_DIGEST": "a" * 64,
            "AEGIS_EXPECTED_ENVIRONMENT": "preview",
        })
        rc, _, _, outputs = _run_verify(env, github_output_path=tmp_path / "outputs")
        assert rc == 1
        # Either taxonomy-correct outcome is acceptable here:
        #   - AttestationEnvelopeShapeInvalid: SDK's from_response raised on
        #     malformed input (action-layer caught + remapped)
        #   - AttestationSignatureSetIncomplete: SDK's from_response tolerated
        #     missing fields (empty signatures list) + verifier-layer rejected
        #     downstream
        # Both surface a "shape problem" to the consumer with an AEGIS-taxonomy
        # error_class. Both belong to the documented fail-closed surface.
        assert outputs["error-class"] in {
            "AttestationEnvelopeShapeInvalid",
            "AttestationSignatureSetIncomplete",
        }


# ─────────────────────────────────────────────────────────────────────────────
# TestEnvelopeParsing — inline vs @path forms
# ─────────────────────────────────────────────────────────────────────────────

class TestEnvelopeParsing:
    def test_inline_envelope_json(self, tmp_path: Path):
        """Inline envelope JSON (no @ prefix) is parsed identically to @path."""
        m = MANIFEST["envelope_valid_preview"]
        envelope_json = (FIXTURES / m["path"]).read_text()
        env = _common_env()
        env.update({
            "AEGIS_ENVELOPE": envelope_json,
            "AEGIS_EXPECTED_DIGEST": m["artifact_digest"],
            "AEGIS_EXPECTED_ENVIRONMENT": m["environment"],
        })
        rc, _, _, outputs = _run_verify(env, github_output_path=tmp_path / "outputs")
        assert rc == 0
        assert outputs["valid"] == "true"
        assert outputs["decision-id"] == m["decision_id"]

    def test_at_path_workspace_relative(self, tmp_path: Path):
        """@<workspace-relative-path> resolves under $GITHUB_WORKSPACE."""
        m = MANIFEST["envelope_valid_preview"]
        # Copy the envelope into tmp_path so we test workspace-relative resolution
        envelope_copy = tmp_path / "my-envelope.json"
        envelope_copy.write_bytes((FIXTURES / m["path"]).read_bytes())

        env = _common_env()
        env.update({
            "AEGIS_ENVELOPE": "@my-envelope.json",  # relative to GITHUB_WORKSPACE
            "AEGIS_EXPECTED_DIGEST": m["artifact_digest"],
            "AEGIS_EXPECTED_ENVIRONMENT": m["environment"],
        })
        rc, _, _, outputs = _run_verify(
            env, github_output_path=tmp_path / "outputs", cwd=tmp_path
        )
        assert rc == 0
        assert outputs["valid"] == "true"


# ─────────────────────────────────────────────────────────────────────────────
# TestOutputEmission — KEY=VALUE format to $GITHUB_OUTPUT
# ─────────────────────────────────────────────────────────────────────────────

class TestOutputEmission:
    def test_github_output_file_contains_all_9_keys(self, tmp_path: Path):
        m = MANIFEST["envelope_valid_preview"]
        env = _common_env()
        env.update({
            "AEGIS_ENVELOPE": f"@{FIXTURES / m['path']}",
            "AEGIS_EXPECTED_DIGEST": m["artifact_digest"],
            "AEGIS_EXPECTED_ENVIRONMENT": m["environment"],
        })
        output_file = tmp_path / "github-output"
        rc, _, _, outputs = _run_verify(env, github_output_path=output_file)
        assert rc == 0
        # Verify all 9 documented outputs are present
        expected_keys = {
            "valid", "error-class", "decision-id", "artifact-digest",
            "environment", "policy-version", "expires-at", "nonce",
            "replay-checked",
        }
        assert set(outputs.keys()) == expected_keys
        # No KEY=VALUE pair has embedded newline (line-based format invariant)
        for line in output_file.read_text().splitlines():
            assert "\n" not in line


# ─────────────────────────────────────────────────────────────────────────────
# TestWarningOnNoReplayStore
# ─────────────────────────────────────────────────────────────────────────────

class TestWarningOnNoReplayStore:
    def test_unset_replay_store_emits_warning(self, tmp_path: Path):
        """replay-store-path unset → ::warning:: + replay-checked=false."""
        m = MANIFEST["envelope_valid_preview"]
        env = _common_env()
        env.update({
            "AEGIS_ENVELOPE": f"@{FIXTURES / m['path']}",
            "AEGIS_EXPECTED_DIGEST": m["artifact_digest"],
            "AEGIS_EXPECTED_ENVIRONMENT": m["environment"],
            # AEGIS_REPLAY_STORE_PATH intentionally unset
        })
        rc, _, stderr, outputs = _run_verify(env, github_output_path=tmp_path / "outputs")
        assert rc == 0
        assert outputs["valid"] == "true"
        assert outputs["replay-checked"] == "false"
        assert "::warning::" in stderr
        assert "replay-store-path not set" in stderr


# ─────────────────────────────────────────────────────────────────────────────
# TestPhase2Regression — regression coverage for /quality-gate Phase 2 bug-hunt
# findings (cycle 1). Each test guards against a specific previously-shipped
# bug surface so subsequent refactors trip the right alarm bell.
# ─────────────────────────────────────────────────────────────────────────────

class TestPhase2Regression:
    def test_fixture_envelope_uses_camelcase_payloadType_key(self):
        """Regression for Lane B Agent 1 F1: fixture must use canonical
        camelCase 'payloadType' (matches SDK DSSEEnvelope.to_dict + the
        in-toto + DSSE v1 JSON wire format). The snake_case 'payload_type'
        was silently accepted by SDK's default-fallback in from_response,
        masking the wire-format drift."""
        envelope = json.loads((FIXTURES / "envelope-valid-preview.json").read_text())
        assert "payloadType" in envelope, (
            "Fixture envelope MUST use camelCase 'payloadType' key per in-toto "
            "+ DSSE v1 JSON wire format. The SDK falls back to a default if "
            "this key is missing — a regression would silently pass the "
            "happy path while hiding the contract drift."
        )
        assert envelope["payloadType"] == "application/vnd.in-toto+json"

    def test_malformed_expected_digest_rejected(self, tmp_path: Path):
        """Regression for Lane B Agent 1 F7: AEGIS_EXPECTED_DIGEST must be
        validated for hex/length BEFORE flowing to the SDK. A malformed
        input should emit AttestationEnvelopeShapeInvalid (configuration
        error), NOT bleed into AttestationDigestMismatch (which the SDK
        would emit on legitimate-but-different hex)."""
        m = MANIFEST["envelope_valid_preview"]
        env = _common_env()
        env.update({
            "AEGIS_ENVELOPE": f"@{FIXTURES / m['path']}",
            "AEGIS_EXPECTED_DIGEST": "not-a-hex-digest",  # wrong length + wrong charset
            "AEGIS_EXPECTED_ENVIRONMENT": m["environment"],
        })
        rc, _, _, outputs = _run_verify(env, github_output_path=tmp_path / "outputs")
        assert rc == 1
        assert outputs["valid"] == "false"
        assert outputs["error-class"] == "AttestationEnvelopeShapeInvalid"

    def test_short_expected_digest_rejected(self, tmp_path: Path):
        """Regression for Lane B Agent 1 F7: 63-char hex still triggers shape
        invalid (must be exactly 64). Edge-of-validity guard."""
        m = MANIFEST["envelope_valid_preview"]
        env = _common_env()
        env.update({
            "AEGIS_ENVELOPE": f"@{FIXTURES / m['path']}",
            "AEGIS_EXPECTED_DIGEST": "a" * 63,  # one char short
            "AEGIS_EXPECTED_ENVIRONMENT": m["environment"],
        })
        rc, _, _, outputs = _run_verify(env, github_output_path=tmp_path / "outputs")
        assert rc == 1
        assert outputs["error-class"] == "AttestationEnvelopeShapeInvalid"

    def test_binary_at_path_envelope_input_rejected(self, tmp_path: Path):
        """Regression for Lane B Agent 1 F6: pointing @path at a non-UTF-8
        binary file (e.g., a key blob) must NOT crash the action with an
        uncaught UnicodeDecodeError. Should map to AttestationEnvelopeShapeInvalid."""
        binary_path = tmp_path / "binary-not-utf8.bin"
        # Bytes invalid as UTF-8 (e.g., a lone 0xff in non-leading position)
        binary_path.write_bytes(b"\xff\xfe\x00\x80\xc0\xc1")
        env = _common_env()
        env.update({
            "AEGIS_ENVELOPE": f"@{binary_path}",
            "AEGIS_EXPECTED_DIGEST": "a" * 64,
            "AEGIS_EXPECTED_ENVIRONMENT": "preview",
        })
        rc, _, _, outputs = _run_verify(env, github_output_path=tmp_path / "outputs")
        assert rc == 1
        assert outputs["error-class"] == "AttestationEnvelopeShapeInvalid"

    def test_subprocess_isolates_inherited_github_output(self, tmp_path: Path):
        """Regression for Lane B Agent 1 F5 (cycle 2 hardened per Agent 1
        F1): parent process's GITHUB_OUTPUT must NOT leak into the
        subprocess. Set a stale GITHUB_OUTPUT in os.environ, then call
        _run_verify WITHOUT github_output_path so the helper does NOT
        override GITHUB_OUTPUT post-strip. If the strip fires correctly,
        the subprocess sees no GITHUB_OUTPUT and falls back to the
        ::github-output:: stdout block; the stale file stays untouched.
        If the strip is REMOVED (regression), the subprocess would inherit
        and write to the stale path — this assertion catches that.

        The original cycle-1 test passed github_output_path which made the
        helper unconditionally override GITHUB_OUTPUT, masking whether the
        strip-loop actually fired. Cycle 2 reshapes the test so the strip
        is the ONLY thing standing between the leak and the assertion.
        """
        stale_output = tmp_path / "stale_should_be_empty.txt"
        # Pollute os.environ to simulate a developer running pytest under
        # a host Actions session OR with an interrupted prior subprocess
        os.environ["GITHUB_OUTPUT"] = str(stale_output)
        os.environ["GITHUB_WORKSPACE"] = "/should/not/be/inherited"
        try:
            m = MANIFEST["envelope_valid_preview"]
            env = _common_env()
            env.update({
                "AEGIS_ENVELOPE": f"@{FIXTURES / m['path']}",
                "AEGIS_EXPECTED_DIGEST": m["artifact_digest"],
                "AEGIS_EXPECTED_ENVIRONMENT": m["environment"],
            })
            # CRITICAL: pass github_output_path=None so _run_verify does NOT
            # override GITHUB_OUTPUT after the strip. Without the strip, the
            # subprocess would inherit the stale path and write there.
            rc, _, _, outputs = _run_verify(env, github_output_path=None)
        finally:
            del os.environ["GITHUB_OUTPUT"]
            del os.environ["GITHUB_WORKSPACE"]

        assert rc == 0
        assert outputs["valid"] == "true"
        # Stale file MUST NOT have been written to: if the GITHUB_* strip
        # is removed in a future refactor, the subprocess would inherit the
        # stale path and `stale_output.exists()` would become True →
        # assertion fails → regression caught.
        assert not stale_output.exists(), (
            "Subprocess wrote to inherited GITHUB_OUTPUT — env var isolation "
            "regression: the GITHUB_* strip in _run_verify did not fire."
        )

    def test_override_env_vars_ignored_without_fixture_mode_sentinel(self, tmp_path: Path):
        """Regression for /quality-gate Phase 3 ultrathink probe 4:
        AEGIS_KEYS_DIR_OVERRIDE + AEGIS_POLICY_PATH_OVERRIDE MUST be IGNORED
        when AEGIS_INTERNAL_FIXTURE_MODE is unset. This neutralizes a
        defense-in-depth gap where a compromised prior step in a consumer
        workflow could `echo "AEGIS_KEYS_DIR_OVERRIDE=./malicious" >>
        $GITHUB_ENV` to redirect the action at attacker-controlled keys.

        Without the sentinel, this test sets overrides → verify_action.py
        falls back to production `keys/` + `policy/verifier-policy-v1.yaml`
        → loads ed25519 raw with SHA `33378f58…` → compares to policy
        required_keyids `33378f58…` → fingerprint parity holds → THEN tries
        to verify the test-key-signed envelope against PRODUCTION ed25519
        public key → signature mismatch → AttestationEd25519VerifyFailed.

        WITH the sentinel (covered by every other test via _common_env),
        the action loads the test keys + test policy → verifies test
        envelope successfully → happy path.
        """
        m = MANIFEST["envelope_valid_preview"]
        env = {
            # Set OVERRIDE vars but DO NOT set AEGIS_INTERNAL_FIXTURE_MODE.
            # Production consumers experience exactly this state if a
            # malicious prior step has tried to redirect us.
            "AEGIS_KEYS_DIR_OVERRIDE": str(FIXTURES / "test-keys"),
            "AEGIS_POLICY_PATH_OVERRIDE": str(FIXTURES / "policy-test-v1.yaml"),
            "AEGIS_ENVELOPE": f"@{FIXTURES / m['path']}",
            "AEGIS_EXPECTED_DIGEST": m["artifact_digest"],
            "AEGIS_EXPECTED_ENVIRONMENT": m["environment"],
        }
        rc, _, _, outputs = _run_verify(env, github_output_path=tmp_path / "outputs")
        # Action loaded PRODUCTION keys (overrides ignored). The test-key-
        # signed envelope's Ed25519 signature fails to verify against the
        # production Ed25519 public key → AttestationEd25519VerifyFailed.
        # The exact error_class isn't the load-bearing assertion — what
        # matters is that the action DID NOT load the test fixtures.
        assert rc == 1
        assert outputs["valid"] == "false"
        # The error MUST be a downstream cryptographic failure, NOT a
        # success — if the overrides had taken effect, the verifier would
        # have happily accepted the test-signed envelope.
        assert outputs["error-class"] in {
            "AttestationEd25519VerifyFailed",
            "AttestationMLDSAVerifyFailed",
            "AttestationKeyFingerprintMismatch",
        }, (
            f"Unexpected error_class {outputs['error-class']!r} — if the "
            "overrides took effect, this would emit valid=true instead, "
            "indicating the sentinel gate failed."
        )

    def test_replay_store_write_failure_marks_replay_unchecked(self, tmp_path: Path):
        """Regression for Lane B Agent 1 F4: when the replay-store-path
        points at a non-writable location, the action MUST emit
        replay-checked=false (NOT 'true'). 'true' would falsely tell the
        consumer the audit trail is durable when in fact the append failed."""
        # Create a read-only directory; replay-store path points inside it.
        # mkdir succeeds but file write fails with EACCES.
        readonly_dir = tmp_path / "readonly"
        readonly_dir.mkdir()
        # The action creates parent dirs if needed; the FILE write itself
        # is what fails. Make the dir read-only AFTER creation.
        readonly_dir.chmod(0o555)
        try:
            m = MANIFEST["envelope_valid_preview"]
            env = _common_env()
            env.update({
                "AEGIS_ENVELOPE": f"@{FIXTURES / m['path']}",
                "AEGIS_EXPECTED_DIGEST": m["artifact_digest"],
                "AEGIS_EXPECTED_ENVIRONMENT": m["environment"],
                "AEGIS_REPLAY_STORE_PATH": str(readonly_dir / "replay.log"),
            })
            rc, _, stderr, outputs = _run_verify(
                env, github_output_path=tmp_path / "outputs", cwd=tmp_path
            )
        finally:
            # Restore writability so pytest tmp_path teardown works
            readonly_dir.chmod(0o755)

        # Crypto verify succeeded; replay-store I/O failed.
        assert rc == 0, f"unexpected rc={rc}; outputs={outputs}"
        assert outputs["valid"] == "true"
        # CRITICAL: replay-checked MUST be 'false' when write failed
        assert outputs["replay-checked"] == "false", (
            "replay-checked must be 'false' when store-write failed; "
            "'true' would falsely claim the audit trail is durable."
        )
        # Warning must be visible in stderr
        assert "::warning::" in stderr
        assert "replay-store-path I/O" in stderr
